In [1]:
%reload_ext nb_black

<IPython.core.display.Javascript object>

# NumPy Tutorial - PART 3

**Ref: [Python NumPy Tutorial for Beginners](https://youtu.be/QUT1VHiLmmI) by [freeCodeCamp.org](https://www.freecodecamp.org/)**

#### Load and configure NumPy library

In [2]:
import numpy as np

print("NumPy version:", np.__version__)

np.set_printoptions(linewidth=130)  # Line width: Maximum 130 chacters in the output, post which it will continue in next line.

NumPy version: 1.20.3


<IPython.core.display.Javascript object>

## Advance Concepts

### Copying NumPy arrays

NumPy uses reference type assignment hence direct assignment of an array to new variable does not copy the array elements. 
```python
b = a  # Does not copy `a` to `b`.
```

In [3]:
a = np.array([1, 2, 3])
b = a

b[1] = 99

print("Array `a`: ", a)
print("Array `b`: ", b)

c = a.copy()
c[2] = -1

print("Array `c`: ", c)

Array `a`:  [ 1 99  3]
Array `b`:  [ 1 99  3]
Array `c`:  [ 1 99 -1]


<IPython.core.display.Javascript object>

### Mathematics

Element wise math operations

### Quiz 3

Create below array using NumPy and extract blue, green and red patterns:

![Quiz 3](Quiz_3.jpg)

In [4]:
arr = np.array(np.arange(1, 31), dtype="int8").reshape((6, 5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]], dtype=int8)

<IPython.core.display.Javascript object>

#### Blue pattern

In [5]:
arr[2:4, 0:2]

array([[11, 12],
       [16, 17]], dtype=int8)

<IPython.core.display.Javascript object>

#### Green pattern

In [6]:
arr[[0, 1, 2, 3], [1, 2, 3, 4]]  # [[row_indexes], [col_indexes]]
# or 
# arr[range(0, 4), range(1, 5)]

array([ 2,  8, 14, 20], dtype=int8)

<IPython.core.display.Javascript object>

#### Red pattern

In [7]:
arr[[0, -2, -1], -2:]

array([[ 4,  5],
       [24, 25],
       [29, 30]], dtype=int8)

<IPython.core.display.Javascript object>