In [1]:
%reload_ext nb_black

<IPython.core.display.Javascript object>

# NumPy Tutorial - PART 2

**Ref: [Python NumPy Tutorial for Beginners](https://youtu.be/QUT1VHiLmmI) by [freeCodeCamp.org](https://www.freecodecamp.org/)**

#### Load and configure NumPy library

In [2]:
import numpy as np

print("NumPy version:", np.__version__)

np.set_printoptions(linewidth=130)  # Line width: Maximum 130 characters in the output, post which it will continue in next line.

NumPy version: 1.20.3


<IPython.core.display.Javascript object>

## NumPy Array Operations

### Accessing specific elements, rows, columns etc

In [3]:
arr = np.array(
    [
        [1, 2, 3, 4, 5, 6, 7],
        [8, 9, 10, 11, 12, 13, 14],
        [7, 6, 5, 4, 3, 2, 1],
    ]
)

print("Arrary:")
print(arr)

print("Shape:", arr.shape)

Arrary:
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [ 7  6  5  4  3  2  1]]
Shape: (3, 7)


<IPython.core.display.Javascript object>

Get elements `5` ,  `8` and `13` from above array.

In [4]:
print("Fetching 5 from array `arr`:", arr[0, 4])  # arr[row_index, col_index]
print("Fetching 8 from array `arr`:", arr[1, 0])  # arr[row_index, col_index]
print("Fetching 8 from array `arr`:", arr[1, -2])  # arr[row_index, col_index]

Fetching 5 from array `arr`: 5
Fetching 8 from array `arr`: 8
Fetching 8 from array `arr`: 13


<IPython.core.display.Javascript object>

Get specific row and column entirely.

In [5]:
print("All elements from first row:", arr[0, :])
print("All elements from third column:", arr[:, 2])

All elements from first row: [1 2 3 4 5 6 7]
All elements from third column: [ 3 10  5]


<IPython.core.display.Javascript object>

Get subset `[9, 11, 13]` from second row. Syntax for extracting subset from a row:

```python
arr[row_index, start_index:end_index:step_size]
```
> **Note: The `end_index` is not inclusive**:

In [6]:
arr[1, 1:6:2]

array([ 9, 11, 13])

<IPython.core.display.Javascript object>

Get subset `[13, 2]` from last but one column. Syntax for extracting subset from a column.

```python
arr[start_index:end_index:step_size, col_index]
```

> **Note: The `end_index` is not inclusive**:

In [7]:
arr[1:3, -2]

array([13,  2])

<IPython.core.display.Javascript object>

### Changing specific elements, rows, columns etc

In [8]:
arr = np.array(
    [
        [100, 11, 54],
        [23, 7, 0],
    ],
    dtype="int8",
)
arr

array([[100,  11,  54],
       [ 23,   7,   0]], dtype=int8)

<IPython.core.display.Javascript object>

Change element `54` in _first row_, _third column_ with `3`.

In [9]:
arr[0, 2] = 3
arr

array([[100,  11,   3],
       [ 23,   7,   0]], dtype=int8)

<IPython.core.display.Javascript object>

Change all elements in second row `[23, 7, 0]` with **similar** value `99`.

In [10]:
arr[1] = 99
arr

array([[100,  11,   3],
       [ 99,  99,  99]], dtype=int8)

<IPython.core.display.Javascript object>

Trying to change value to a different datatype.

> **Note: Booleans are explicitly considered as integers in Python 2 and 3.**

In [11]:
# arr[0] = "Hello" # Does not work. Throws error.
# arr[0] = None # Does not work. Throws error.
arr[0] = True
arr

array([[ 1,  1,  1],
       [99, 99, 99]], dtype=int8)

<IPython.core.display.Javascript object>

Change all elements in first column `[1, 99]` with **similar** value `47`.

In [12]:
arr[:, 0] = 47
arr

array([[47,  1,  1],
       [47, 99, 99]], dtype=int8)

<IPython.core.display.Javascript object>

Change all elements in second row `[47, 99, 99]` with **different** values `[0, -2, 84]`.

> **Note: When updating multiple values of a row / column we must respect its Shape.**

In [13]:
# arr[1] = [0, -3] # Does not work. Throws error.
arr[1] = [0, -2, 84]
arr

array([[47,  1,  1],
       [ 0, -2, 84]], dtype=int8)

<IPython.core.display.Javascript object>

Changing all elements in third column `[1, 84]` with **different** values `[79, 100]`.

In [14]:
# arr[:, 2] = [79] # Also works
arr[:, 2] = [79, 100]
arr

array([[ 47,   1,  79],
       [  0,  -2, 100]], dtype=int8)

<IPython.core.display.Javascript object>

### Quiz 1: 3-D Matrix

Create below 3-D matrix using NumPy array:

![Sample 3-D Matrix](Quiz_1.svg)

In [15]:
td_mat = np.array(
    [
        [[7, 1], [9, 4], [2, 3]],
        [[4, -2], [0, -5], [8, 0]],
        [[1, -9], [3, -7], [6, 9]],
        [[5, -3], [8, -1], [4, 7]],
    ],
    # All negative numbers represent hidden elements in the image.
    dtype="int8",
)

print("3-D Matrix:")
print(td_mat)

print("Shape:", td_mat.shape)

3-D Matrix:
[[[ 7  1]
  [ 9  4]
  [ 2  3]]

 [[ 4 -2]
  [ 0 -5]
  [ 8  0]]

 [[ 1 -9]
  [ 3 -7]
  [ 6  9]]

 [[ 5 -3]
  [ 8 -1]
  [ 4  7]]]
Shape: (4, 3, 2)


<IPython.core.display.Javascript object>

Get elements `[[4, 0], [1, 3]]` from the above 3-D matrix.

In [16]:
# [x_axis, y_axis, z_axis]
# [1_axis, 0_axis, 2_axis]
# [rows, columns, Z-index]
td_mat[1:3, 0:2, 0]

array([[4, 0],
       [1, 3]], dtype=int8)

<IPython.core.display.Javascript object>

### Initializing Different Types of Arrays

#### All Zeros matrix

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

<IPython.core.display.Javascript object>

In [18]:
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

<IPython.core.display.Javascript object>

#### All Ones matrix

In [19]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

<IPython.core.display.Javascript object>

In [20]:
np.ones((1, 3, 8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

<IPython.core.display.Javascript object>

In [21]:
np.ones((2, 5), dtype="int8")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

<IPython.core.display.Javascript object>

#### Non-Zeros / Non-Ones matrix

Create matrix of shape - `(3, 9)` - three rows and nine columns with all elements being `47` of datatype `int8`.

In [22]:
np.full((3, 9), 47, dtype="int8")

array([[47, 47, 47, 47, 47, 47, 47, 47, 47],
       [47, 47, 47, 47, 47, 47, 47, 47, 47],
       [47, 47, 47, 47, 47, 47, 47, 47, 47]], dtype=int8)

<IPython.core.display.Javascript object>

In [23]:
arr = np.array([100, 47, 66], dtype="int32")
print("Array `arr`:", arr)

nar1 = np.full_like(arr, 4)
print("New array `nar1` with shape of `arr`:", nar1)

# or

nar2 = np.full(arr.shape, 4)
print("New array `nar2` with shape of `arr`:", nar2)

Array `arr`: [100  47  66]
New array `nar1` with shape of `arr`: [4 4 4]
New array `nar2` with shape of `arr`: [4 4 4]


<IPython.core.display.Javascript object>

#### Random Decimal matrix

In [24]:
np.random.rand(2, 3, 7)  # Pass the required shape as function paramets.

array([[[0.58063897, 0.07547732, 0.79508575, 0.44965035, 0.27173693, 0.03620963, 0.32538712],
        [0.09321295, 0.56901718, 0.98084301, 0.2416608 , 0.69149727, 0.30419422, 0.89553746],
        [0.69431822, 0.65449152, 0.25975544, 0.6116095 , 0.46383718, 0.99786724, 0.20708409]],

       [[0.95093352, 0.23036866, 0.40967048, 0.4638276 , 0.57093751, 0.26631529, 0.59908168],
        [0.45022942, 0.1655905 , 0.93892726, 0.05214085, 0.81318888, 0.48314301, 0.61357702],
        [0.01467856, 0.21560484, 0.30445835, 0.02176561, 0.35796478, 0.50390639, 0.60120975]]])

<IPython.core.display.Javascript object>

In [25]:
np.random.random_sample(arr.shape)

array([0.43526387, 0.72814015, 0.72166006])

<IPython.core.display.Javascript object>

#### Random Integer matrix

Syntax:

```python
np.random.randint(start_index, end_index)
np.random.randint(start_index, end_index, size=(row, column))
```
1. Start index - `start_index` - is optional. If not present array starts from zero.
2. End index - `end_index` - is not inclusive.

In [26]:
np.random.randint(2, 100)

28

<IPython.core.display.Javascript object>

In [27]:
np.random.randint(10, size=(10))

array([8, 1, 1, 7, 3, 3, 6, 5, 2, 0])

<IPython.core.display.Javascript object>

In [28]:
np.random.randint(47, size=(3, 20))

array([[39, 33, 18, 11, 19,  9,  4, 34, 23,  4, 12,  1, 10, 38, 18,  9, 43, 19,  4,  1],
       [44, 19, 24,  3, 43, 19,  9, 18, 30, 18, 33, 45,  7, 18, 21, 32, 30, 11, 46, 26],
       [25, 28,  7, 25, 30,  6,  7,  3, 45, 44, 22, 38, 23, 18, 26, 25, 20, 36,  2, 17]])

<IPython.core.display.Javascript object>

#### Identity matrix

All diagonal elements are `1` and all non diagonal elements are `0`.

In [29]:
np.identity(5)  # Creates 5 X 5 identity matrix.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<IPython.core.display.Javascript object>

### Quiz 2

Create below array using NumPy:

![Quiz 2](Quiz_2.jpg)

**STEP 1**: Create 5 X 5 matrix of zeros.

In [50]:
N = input("Enter an odd number greater than 3 to create N X N matrix: ")
N = int(N)

if N < 3 or N % 2 == 0:
    raise Exception("N must be an odd number greater than 3.")

q2_op = np.zeros((N, N), dtype="int8")
q2_op

Enter an odd number greater than 3 to create N X N matrix: 5


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

<IPython.core.display.Javascript object>

**STEP 2**: 

In [51]:
q2_op[[0, -1]] = 1  # Update rows
q2_op[:, [0, -1]] = 1  # Update columns

q2_op

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

<IPython.core.display.Javascript object>

**STEP 3**: 

In [52]:
row, col = q2_op.shape

if row >= 3 and row % 2 != 0 and col >= 3 and col % 2 != 0:
    q2_op[int(row / 2), int(col / 2)] = 9
    print(q2_op)
else:
    print("Please create Square matrix of size greater than 3 X 3 with odd dimensions.")

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


<IPython.core.display.Javascript object>